// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQx0bQbJYazfV4DbkBJ0hV_D16VbGdRWg',
    appId: '1:426298785427:web:2344306b8c260e52c0d766',
    messagingSenderId: '426298785427',
    projectId: 'collegemarksapp',
    authDomain: 'collegemarksapp.firebaseapp.com',
    storageBucket: 'collegemarksapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOxyI7olkhnExA8fXc4OdSppBYnBlSiy0',
    appId: '1:426298785427:android:aab39b30744d19e7c0d766',
    messagingSenderId: '426298785427',
    projectId: 'collegemarksapp',
    storageBucket: 'collegemarksapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8IzcfXtgI7veLlecRUjjoTCF6DwCLNfI',
    appId: '1:426298785427:ios:61f1bef6ccb66e88c0d766',
    messagingSenderId: '426298785427',
    projectId: 'collegemarksapp',
    storageBucket: 'collegemarksapp.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8IzcfXtgI7veLlecRUjjoTCF6DwCLNfI',
    appId: '1:426298785427:ios:61f1bef6ccb66e88c0d766',
    messagingSenderId: '426298785427',
    projectId: 'collegemarksapp',
    storageBucket: 'collegemarksapp.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQx0bQbJYazfV4DbkBJ0hV_D16VbGdRWg',
    appId: '1:426298785427:web:e11f3c7ad9ad4bf8c0d766',
    messagingSenderId: '426298785427',
    projectId: 'collegemarksapp',
    authDomain: 'collegemarksapp.firebaseapp.com',
    storageBucket: 'collegemarksapp.firebasestorage.app',
  );
}
